export enum Permission {
  // User permissions
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  
  // Product permissions
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  READ_PRODUCT = 'READ_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  
  // Order permissions
  CREATE_ORDER = 'CREATE_ORDER',
  READ_ORDER = 'READ_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  MANAGE_ALL_ORDERS = 'MANAGE_ALL_ORDERS',
  
  // Category permissions
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  READ_CATEGORY = 'READ_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  
  // Review permissions
  CREATE_REVIEW = 'CREATE_REVIEW',
  READ_REVIEW = 'READ_REVIEW',
  UPDATE_REVIEW = 'UPDATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',
  MODERATE_REVIEWS = 'MODERATE_REVIEWS',
  
  // Inventory permissions
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  
  // Discount permissions
  CREATE_DISCOUNT = 'CREATE_DISCOUNT',
  READ_DISCOUNT = 'READ_DISCOUNT',
  UPDATE_DISCOUNT = 'UPDATE_DISCOUNT',
  DELETE_DISCOUNT = 'DELETE_DISCOUNT',
  
  // Report permissions
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_REPORTS = 'EXPORT_REPORTS',
}

